services:
  db:
    image: mysql:8.0
    container_name: carwash_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_car_wash
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      retries: 10
      timeout: 5s

  api:
    build: .
    container_name: carwash_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

  test:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.test
    volumes:
      - .:/app
    command: pytest -v

volumes:
  mysql_data: